### ISSUE TITLE
Cannot index into a null array ..

### ISSUE THREAD

**Issue by vidhyashankarkm** [dimitri-furman/sqldb-migration#1]
Hi, i am getting error while running .\Invoke-BacpacUploadAndImport.ps1
(For testing purpose , manually ran the Get-AzureRmStorageAccountKey -ResourceGroupName "RGANeme" -Name "Name" it is returning value ..  )

i am not sure how to fix this .. could you please help.
 
Cannot index into a null array.
At D:\DAC\bacpac\Invoke-BacpacUploadAndImport.ps1:99 char:1
+ $StorageAccountKey = (Get-AzureRmStorageAccountKey -ResourceGroupName $StorageRe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : NullArray

**Comment by dimitri-furman** [comment]
@vidhyashankarkm This can happen if you use an older version of Azure PowerShell. The syntax has changed starting with v1.4. See Example 2 in https://docs.microsoft.com/en-us/powershell/resourcemanager/azurerm.storage/v1.2.0/get-azurermstorageaccountkey. The script uses the newer syntax. You can try upgrading to the latest version of Azure PowerShell, or change Value[0] to Key1 in that line of code.

Please reopen this issue if this does not resolve the problem.

**Comment by vidhyashankarkm** [comment]
Thanks Dmitri .. it works with power-shell upgrade !! thanks a lot .

one more question , from automation perspective is there any way we can give all password as input ? since its asking passwords as popups.

**Comment by dimitri-furman** [comment]
@vidhyashankarkm Yes, you can add a SecureString parameter for the password and get rid of the ui.PromptForCredential prompt. But you will need to find a way to avoid storing the password in plain text. If you use Azure Automation, you can store the credential as an automation asset, convert this sample script to a runbook, and pass the credential to the runbook.
